### ISSUE TITLE
error? Traceback (most recent call last):

### ISSUE THREAD

**Issue by stephen6611** [bro-11/flasher#11]
Traceback (most recent call last):
  File "C:\Users\*\SHOPEEE\flasher-master\main.py", line 175, in <module>
    main()
  File "C:\Users\*\SHOPEEE\flasher-master\main.py", line 143, in main
    flash_sale_start = datetime.fromtimestamp(item.upcoming_flash_sale.start_time)
TypeError: an integer is required (got type NoneType)

ini kira" penyebabnya error atau gagal checkout karna stok habis bro?

**Comment by bro-11** [comment]
error bang, udh ane fix barusan
