### ISSUE TITLE
ini penyebab Errornya kenapa bang?

### ISSUE THREAD

**Issue by Alpha-Iso** [bro-11/flasher#12]
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    main()
  File "main.py", line 102, in main
    bot = ShopeeBot(pickle.load(f))
  File "D:\Bot Shopee\flasher-master\flasher\bot.py", line 41, in __init__
    self.session, self.user = requests.Session(), ShopeeBot.login(cookie)
  File "D:\Bot Shopee\flasher-master\flasher\bot.py", line 32, in login
    data["default_address"]("address"),
TypeError: 'NoneType' object is not callable

**Comment by Alpha-Iso** [comment]
udh bisa bang, ternyata alamat di akunnya blum di atur awkowkowko
