### ISSUE TITLE
masih ga bisa checkout gan

### ISSUE THREAD

**Issue by qiwiled** [bro-11/flasher#6]
![Screenshot_2021-05-29-13-28-28-63_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/44135803/120060411-f34a9e80-c081-11eb-9214-b7f35f5ac657.jpg)

**Comment by qiwiled** [comment]
ini eror saat menggunakan pembayaran COD

[*] Mengambil Informasi User...
[*] Welcome qiwiled

[*] Masukkan Url Barang
[?] Url: https://shopee.co.id/product/51115741/3140578171?smtt=0.31460398-1622269448.9
--------------------------------
 Nama:  Log On FAST XL C26 Home Charger Dual USB 2.4A
 Harga:  18900
 Brand:  None
 Stok:  197
 Lokasi Toko:  KOTA JAKARTA UTARA
--------------------------------

[*] Pilih Metode Pembayaran
[1] Alfamart
[2] Indomart iSaku
[3] Akulaku
[4] Transfer Bank
[5] COD (Bayar di Tempat)
[6] ShopeePay

[?]  Pilihan: 5

[*] Flash Sale telah tiba
[*] Menambah item ke Cart...
[*] Checkout...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/flasher/main.py", line 181, in <module>
    main()
  File "/data/data/com.termux/files/home/flasher/main.py", line 161, in main
    ok = bot.checkout(cart_item, Payment.from_channel(selected_payment_channel, selected_option_info))
  File "/data/data/com.termux/files/home/flasher/flasher/bot.py", line 117, in checkout
    return "error" not in resp.json() and resp.ok
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~/flasher $

**Comment by Alpha-Iso** [comment]
yaiyalah ga bisa bang, itu barangnya khusus pembayaran shopeepay

![Screenshot 2021-05-29 135040](https://user-images.githubusercontent.com/84896824/120060950-e11e2f80-c084-11eb-80b3-ca5ffa8bbdba.png)

**Comment by bro-11** [comment]
ok terimakasih sudah ngasih tau, nanti ane coba fix

**Comment by qiwiled** [comment]
oke bang,setelah memakai script hasil fix yang baru sudah berhasil checkout semua
